/**
 * Human-readable labels for organization profile keys (minister CSV / OrganizationProfile.data).
 * Used for Education and Health template profile UI. Add new keys here when new fields are added.
 */

function titleCase(key: string): string {
  return key
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

import type { Language } from '../components/i18n/LanguageContext';

const EDUCATION_LABELS: Record<string, { en: string; or: string }> = {
  block_ulb: { en: 'Block / ULB', or: 'ବ୍ଲକ୍ / ULB' },
  gp_ward: { en: 'GP / Ward', or: 'ଜି.ପି. / ୱାର୍ଡ' },
  village: { en: 'Village', or: 'ଗ୍ରାମ' },
  name_of_school: { en: 'Name of School', or: 'ବିଦ୍ୟାଳୟର ନାମ' },
  school_id: { en: 'School ID', or: 'ବିଦ୍ୟାଳୟ ଆଇଡି' },
  esst_year: { en: 'ESST Year', or: 'ସ୍ଥାପନ ବର୍ଷ' },
  category: { en: 'Category', or: 'ଶ୍ରେଣୀ' },
  class_i: { en: 'Class I', or: 'ପ୍ରଥମ ଶ୍ରେଣୀ' },
  class_ii: { en: 'Class II', or: 'ଦ୍ୱିତୀୟ ଶ୍ରେଣୀ' },
  class_iii: { en: 'Class III', or: 'ତୃତୀୟ ଶ୍ରେଣୀ' },
  class_iv: { en: 'Class IV', or: 'ଚତୁର୍ଥ ଶ୍ରେଣୀ' },
  class_v: { en: 'Class V', or: 'ପଞ୍ଚମ ଶ୍ରେଣୀ' },
  class_vi: { en: 'Class VI', or: 'ଷଷ୍ଠ ଶ୍ରେଣୀ' },
  class_vii: { en: 'Class VII', or: 'ସପ୍ତମ ଶ୍ରେଣୀ' },
  class_viii: { en: 'Class VIII', or: 'ଅଷ୍ଟମ ଶ୍ରେଣୀ' },
  class_ix: { en: 'Class IX', or: 'ନବମ ଶ୍ରେଣୀ' },
  class_x: { en: 'Class X', or: 'ଦଶମ ଶ୍ରେଣୀ' },
  deo_name: { en: 'DEO Name', or: 'DEO ନାମ' },
  deo_contact: { en: 'DEO Contact', or: 'DEO ଯୋଗାଯୋଗ' },
  beo_name: { en: 'BEO Name', or: 'BEO ନାମ' },
  beo_contact: { en: 'BEO Contact', or: 'BEO ଯୋଗାଯୋଗ' },
  brcc_name: { en: 'BRCC Name', or: 'BRCC ନାମ' },
  brcc_contact: { en: 'BRCC Contact', or: 'BRCC ଯୋଗାଯୋଗ' },
  crcc_name: { en: 'CRCC Name', or: 'CRCC ନାମ' },
  crcc_contact: { en: 'CRCC Contact', or: 'CRCC ଯୋଗାଯୋଗ' },
  name_of_hm: { en: 'Name of HM', or: 'ପ୍ରଧାନ ଶିକ୍ଷକଙ୍କ ନାମ' },
  contact_of_hm: { en: 'Contact of HM', or: 'ପ୍ରଧାନ ଶିକ୍ଷକଙ୍କ ଯୋଗାଯୋଗ' },
  no_of_ts: { en: 'No of TS', or: 'ଶିକ୍ଷକ ସଂଖ୍ୟା' },
  no_of_nts: { en: 'Total Non-Teaching Staff', or: 'ମୋଟ ଅଣ-ଶିକ୍ଷକ କର୍ମଚାରୀ' },
  no_of_tgp_pcm: { en: 'No of TGP (PCM)', or: 'TGP (PCM) ସଂଖ୍ୟା' },
  no_of_tgp_cbz: { en: 'No of TGP (CBZ)', or: 'TGP (CBZ) ସଂଖ୍ୟା' },
  no_of_tgt_arts: { en: 'No of TGT (Arts)', or: 'TGT (Arts) ସଂଖ୍ୟା' },
  building_status: { en: 'Building Status', or: 'ଗୃହର ସ୍ଥିତି' },
  no_of_rooms: { en: 'No of Rooms', or: 'କୋଠରୀ ସଂଖ୍ୟା' },
  no_of_smart_class_rooms: { en: 'No of Smart Class Rooms', or: 'ସ୍ମାର୍ଟ କ୍ଲାସ୍ ସଂଖ୍ୟା' },
  science_lab: { en: 'Science Lab', or: 'ବିଜ୍ଞାନାଗାର' },
  toilet_m: { en: 'Toilet (M)', or: 'ଶୌଚାଳୟ (ପୁରୁଷ)' },
  toilet_f: { en: 'Toilet (F)', or: 'ଶୌଚାଳୟ (ମହିଳା)' },
  ramp: { en: 'Ramp', or: 'ରାମ୍ପ' },
  meeting_hall: { en: 'Meeting Hall', or: 'ସଭା ଗୃହ' },
  staff_common_room: { en: 'Staff Common Room', or: 'ଶିକ୍ଷକ ସାଧାରଣ କୋଠରୀ' },
  ncc: { en: 'NCC', or: 'ଏନ୍.ସି.ସି.' },
  nss: { en: 'NSS', or: 'ଏନ୍.ଏସ୍.ଏସ୍.' },
  jrc: { en: 'JRC', or: 'ଜେ.ଆର.ସି.' },
  eco_club: { en: 'Eco Club', or: 'ଇକୋ କ୍ଲବ୍' },
  library: { en: 'Library', or: 'ପାଠାଗାର' },
  icc_head_name: { en: 'ICC Head Name', or: 'ICC ମୁଖ୍ୟଙ୍କ ନାମ' },
  icc_head_contact: { en: 'ICC Head Contact', or: 'ICC ମୁଖ୍ୟଙ୍କ ଯୋଗାଯୋଗ' },
  play_ground: { en: 'Play Ground', or: 'ଖେଳ ପଡିଆ' },
  cycle_stand: { en: 'Cycle Stand', or: 'ସାଇକେଲ ଷ୍ଟାଣ୍ଡ' },
  drinking_water_tw: { en: 'Drinking Water (TW)', or: 'ପାନୀୟ ଜଳ (ନଳକୂପ)' },
  drinking_water_tap: { en: 'Drinking Water (Tap)', or: 'ପାନୀୟ ଜଳ (ଟ୍ୟାପ୍)' },
  drinking_water_overhead_tap: { en: 'Drinking Water (Overhead Tap)', or: 'ପାନୀୟ ଜଳ (ଓଭରହେଡ୍ ଟ୍ୟାପ୍)' },
  drinking_water_aquaguard: { en: 'Drinking Water (Aquaguard)', or: 'ପାନୀୟ ଜଳ (ଆକ୍ୱାଗାର୍ଡ)' },
  latitude: { en: 'Latitude', or: 'ଅକ୍ଷାଂଶ' },
  longitude: { en: 'Longitude', or: 'ଦ୍ରାଘିମା' },
  description: { en: 'Description', or: 'ବିବରଣୀ' },
  institution_id: { en: 'Institution ID', or: 'ଅନୁଷ୍ଠାନ ଆଇଡି' },
  established_year: { en: 'Established Year', or: 'ସ୍ଥାପନ ବର୍ଷ' },
  campus_area_acres: { en: 'Campus Area (Acres)', or: 'କ୍ୟାମ୍ପସ କ୍ଷେତ୍ରଫଳ (ଏକର)' },
  affiliating_university: { en: 'Affiliating University', or: 'ସଂଲଗ୍ନ ବିଶ୍ୱବିଦ୍ୟାଳୟ' },
  autonomous: { en: 'Autonomous', or: 'ସ୍ଵୟଂଶାସିତ' },
  college_type: { en: 'College Type', or: 'ମହାବିଦ୍ୟାଳୟ ପ୍ରକାର' },
  pin_code: { en: 'Pin Code', or: 'ପିନ୍ କୋଡ୍' },
  principal_name: { en: 'Principal Name', or: 'ଅଧ୍ୟକ୍ଷଙ୍କ ନାମ' },
  principal_contact: { en: 'Principal Contact', or: 'ଅଧ୍ୟକ୍ଷଙ୍କ ଯୋଗାଯୋଗ' },
  principal_email: { en: 'Principal Email', or: 'ଅଧ୍ୟକ୍ଷଙ୍କ ଇମେଲ୍' },
  college_phone: { en: 'College Phone', or: 'ମହାବିଦ୍ୟାଳୟ ଫୋନ୍' },
  college_email: { en: 'College Email', or: 'ମହାବିଦ୍ୟାଳୟ ଇମେଲ୍' },
  website: { en: 'Website', or: 'ୱେବସାଇଟ୍' },
  aicte_approval: { en: 'AICTE Approval', or: 'AICTE ଅନୁମୋଦନ' },
  naac: { en: 'NAAC', or: 'NAAC' },
  nba: { en: 'NBA', or: 'NBA' },
  nirf_ranking: { en: 'NIRF Ranking', or: 'NIRF ମାନ୍ୟତା' },
  b_tech_branches_count: { en: 'B.Tech Branches Count', or: 'B.Tech ଶାଖା ସଂଖ୍ୟା' },
  m_tech_programmes_count: { en: 'M.Tech Programmes Count', or: 'M.Tech ପ୍ରୋଗ୍ରାମ ସଂଖ୍ୟା' },
  ph_d: { en: 'Ph.D. Available', or: 'Ph.D. ସୁବିଧା' },
  departments: { en: 'Departments', or: 'ବିଭାଗ ସମୂହ' },
  no_of_labs: { en: 'No of Labs', or: 'ଗବେଷଣାଗାର ସଂଖ୍ୟା' },
  workshop: { en: 'Workshop', or: 'ୱାର୍କସପ୍' },
  hostel: { en: 'Hostel Availability', or: 'ଛାତ୍ରାବାସ ସୁବିଧା' },
  hostel_capacity_boys: { en: 'Hostel Capacity (Boys)', or: 'ଛାତ୍ରାବାସ କ୍ଷମତା (ଛାତ୍ର)' },
  hostel_capacity_girls: { en: 'Hostel Capacity (Girls)', or: 'ଛାତ୍ରାବାସ କ୍ଷମତା (ଛାତ୍ରୀ)' },
  guest_house: { en: 'Guest House', or: 'ଅତିଥି ଭବନ' },
  banking: { en: 'Banking', or: 'ବ୍ୟାଙ୍କିଙ୍ଗ' },
  canteen: { en: 'Canteen', or: 'କ୍ୟାଣ୍ଟିନ' },
  gymnasium: { en: 'Gymnasium', or: 'ବ୍ୟାୟାମଶାଳା' },
  wifi_availability: { en: 'WiFi Availability', or: 'ୱାଇ-ଫାଇ ସୁବିଧା' },
  garden: { en: 'Garden', or: 'ବଗିଚା' },
  transport_fascility: { en: 'Transport Facility', or: 'ପରିବହନ ସୁବିଧା' },
  parking_fascility: { en: 'Parking Facility', or: 'ପାର୍କିଂ ସୁବିଧା' },
  staff_accommodation: { en: 'Staff Accommodation', or: 'କର୍ମଚାରୀ ଆବାସ' },
  security: { en: 'Security', or: 'ସୁରକ୍ଷା' },
  cctv: { en: 'CCTV', or: 'ସିସିଟିଭି' },
  electricity: { en: 'Electricity', or: 'ବିଦ୍ୟୁତ୍ ଶକ୍ତି' },
  grievance_cell_head: { en: 'Grievance Cell Head', or: 'ଅଭିଯୋଗ ପ୍ରକୋଷ୍ଠ ମୁଖ୍ୟ' },
  innovation_and_startup_fascility: { en: 'Innovation & Startup', or: 'ନବସୃଜନ ଓ ଷ୍ଟାର୍ଟଅପ୍' },
  robotics_club: { en: 'Robotics Club', or: 'ରୋବୋଟିକ୍ସ କ୍ଲବ୍' },
  cultural_clubs: { en: 'Cultural Clubs', or: 'ସାଂସ୍କୃତିକ କ୍ଲବ୍' },
  sports_and_athletics_fascility: { en: 'Sports & Athletics', or: 'କ୍ରୀଡ଼ା ଓ ଆଥଲେଟିକ୍ସ' },
  research_projects_count: { en: 'Research Projects Count', or: 'ଗବେଷଣା ପ୍ରକଳ୍ପ ସଂଖ୍ୟା' },
  patents_count: { en: 'Patents Count', or: 'ପ୍ୟାଟେଣ୍ଟ ସଂଖ୍ୟା' },
  mou_count: { en: 'MOU Count', or: 'MOU ସଂଖ୍ୟା' },
  centre_of_excellence: { en: 'Centre of Excellence', or: 'ଉତ୍କର୍ଷ କେନ୍ଦ୍ର' },
  incubation_centre: { en: 'Incubation Centre', or: 'ଇନକ୍ୟୁବେସନ କେନ୍ଦ୍ର' },
  placement_officer_name: { en: 'Placement Officer Name', or: 'ନିଯୁକ୍ତି ଅଧିକାରୀଙ୍କ ନାମ' },
  placement_officer_contact: { en: 'Placement Officer Contact', or: 'ନିଯୁକ୍ତି ଅଧିକାରୀଙ୍କ ଯୋଗାଯୋଗ' },
  placement_percentage: { en: 'Placement Percentage', or: 'ନିଯୁକ୍ତି ପ୍ରତିଶତ' },
  highest_package_lpa: { en: 'Highest Package (LPA)', or: 'ସର୍ବାଧିକ ପ୍ୟାକେଜ୍ (LPA)' },
  dean_registrar_name: { en: 'Dean/Registrar Name', or: 'ଡିନ୍/ରେଜିଷ୍ଟ୍ରାର ନାମ' },
  schorlaship_fascility: { en: 'Scholarship Facility', or: 'ବୃତ୍ତି ସୁବିଧା' },
  notable_awards_or_achievements: { en: 'Notable Awards', or: 'ଉଲ୍ଲେଖନୀୟ ପୁରସ୍କାର' },
  autonomous_since_year: { en: 'Autonomous Since Year', or: 'ସ୍ଵୟଂଶାସିତ ବର୍ଷଠାରୁ' },
  aariia_atal_ranking: { en: 'AARIIA-ATAL Ranking', or: 'AARIIA-ATAL ମାନ୍ୟତା' },
  total_intake_ug_automobile_engineering: { en: 'Intake: Automobile Engineering', or: 'ନାମଲେଖା: ଅଟୋମୋବାଇଲ୍ ଇଞ୍ଜିନିୟରିଂ' },
  total_intake_ug_chemical_engineering: { en: 'Intake: Chemical Engineering', or: 'ନାମଲେଖା: କେମିକାଲ୍ ଇଞ୍ଜିନିୟରିଂ' },
  total_intake_ug_civil_engineering: { en: 'Intake: Civil Engineering', or: 'ନାମଲେଖା: ସିଭିଲ୍ ଇଞ୍ଜିନିୟରିଂ' },
  total_intake_ug_computer_science_engineering: { en: 'Intake: CSE', or: 'ନାମଲେଖା: CSE' },
  total_intake_ug_electrical_engineering: { en: 'Intake: Electrical Engineering', or: 'ନାମଲେଖା: ଇଲେକ୍ଟ୍ରିକାଲ୍ ଇଞ୍ଜିନିୟରିଂ' },
  total_intake_ug_electronics_telecommunication_engineering: { en: 'Intake: E&TC Engineering', or: 'ନାମଲେଖା: E&TC ଇଞ୍ଜିନିୟରିଂ' },
  total_intake_ug_mechanical_engineering: { en: 'Intake: Mechanical Engineering', or: 'ନାମଲେଖା: ମେକାନିକାଲ୍ ଇଞ୍ଜିନିୟରିଂ' },
  total_intake_ug_metallurgical_and_materials_engineering: { en: 'Intake: Metallurgical Engineering', or: 'ନାମଲେଖା: ମେଟାଲର୍ଜିକାଲ୍ ଇଞ୍ଜିନିୟରିଂ' },
  total_intake_ug_production_engineering: { en: 'Intake: Production Engineering', or: 'ନାମଲେଖା: ପ୍ରୋଡକ୍ସନ ଇଞ୍ଜିନିୟରିଂ' },
  total_intake_pg_departments_wise: { en: 'PG Intake (Branch-wise)', or: 'PG ନାମଲେଖା (ଶାଖା ଅନୁସାରେ)' },
  total_no_of_faculty_automobile_engineering: { en: 'Faculty: Automobile Engineering', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: ଅଟୋମୋବାଇଲ୍' },
  total_no_of_faculty_chemical_engineering: { en: 'Faculty: Chemical Engineering', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: କେମିକାଲ୍' },
  total_no_of_faculty_civil_engineering: { en: 'Faculty: Civil Engineering', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: ସିଭିଲ୍' },
  total_no_of_faculty_computer_science_engineering: { en: 'Faculty: CSE', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: CSE' },
  total_no_of_faculty_electrical_engineering: { en: 'Faculty: Electrical Engineering', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: ଇଲେକ୍ଟ୍ରିକାଲ୍' },
  total_no_of_faculty_electronics_telecommunication_engineering: { en: 'Faculty: E&TC Engineering', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: E&TC' },
  total_no_of_faculty_mechanical_engineering: { en: 'Faculty: Mechanical Engineering', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: ମେକାନିକାଲ୍' },
  total_no_of_faculty_metallurgical_and_materials_engineering: { en: 'Faculty: Metallurgical Engineering', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: ମେଟାଲର୍ଜିକାଲ୍' },
  total_no_of_faculty_production_engineering: { en: 'Faculty: Production Engineering', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: ପ୍ରୋଡକ୍ସନ' },
  total_no_of_faculty_basic_science: { en: 'Faculty: Basic Science', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: ବେସିକ ସାଇନ୍ସ' },
  total_no_of_faculty_humanities_and_social_science: { en: 'Faculty: Humanities', or: 'ଅଧ୍ୟାପକ ସଂଖ୍ୟା: ହ୍ୟୁମାନିଟିଜ୍' },
  no_of_labs_brach_wise: { en: 'Labs (Branch-wise)', or: 'ଗବେଷଣାଗାର (ଶାଖା ଅନୁସାରେ)' },
  drinking_water: { en: 'Drinking Water', or: 'ପାନୀୟ ଜଳ' },
  grievance_cell_head_contact: { en: 'Grievance Cell Contact', or: 'ଅଭିଯୋଗ ପ୍ରକୋଷ୍ଠ ଯୋଗାଯୋଗ' },
  anti_ragging_cell_head: { en: 'Anti-Ragging Cell Head', or: 'ଆଣ୍ଟି-ରାଗିଂ ପ୍ରକୋଷ୍ଠ ମୁଖ୍ୟ' },
  anti_ragging_cell_head_contact: { en: 'Anti-Ragging Cell Contact', or: 'ଆଣ୍ଟି-ରାଗିଂ ପ୍ରକୋଷ୍ଠ ଯୋଗାଯୋଗ' },
  placement_percentage_last_year: { en: 'Placement Percentage', or: 'ନିଯୁକ୍ତି ପ୍ରତିଶତ (ଗତ ବର୍ଷ)' },
  centre_of_excellence_comma_separated: { en: 'Centres of Excellence', or: 'ଉତ୍କର୍ଷ କେନ୍ଦ୍ର ସମୂହ' },
  // ITI Specific attributes
  iti_code: { en: 'ITI Code', or: 'ITI କୋଡ୍' },
  state: { en: 'State', or: 'ରାଜ୍ୟ' },
  district: { en: 'District', or: 'ଜିଲ୍ଲା' },
  ownership: { en: 'Ownership', or: 'ମାଲିକାନା' },
  affiliation: { en: 'Affiliation', or: 'ସଂଲଗ୍ନିକରଣ' },
  affiliating_body: { en: 'Affiliating Body', or: 'ସଂଲଗ୍ନକାରୀ ସଂସ୍ଥା' },
  total_trades_count: { en: 'Total Trades', or: 'ମୋଟ ଟ୍ରେଡ୍ ସଂଖ୍ୟା' },
  trades_offered: { en: 'Trades Offered', or: 'ଉପଲବ୍ଧ ଟ୍ରେଡ୍ ସମୂହ' },
  total_seats_all_trades: { en: 'Total Seats', or: 'ମୋଟ ଆସନ ସଂଖ୍ୟା' },
  trade_wise_seats: { en: 'Trade-wise Seats', or: 'ଟ୍ରେଡ୍ ଅନୁସାରେ ଆସନ' },
  total_trainees_enrolled: { en: 'Total Trainees Enrolled', or: 'ମୋଟ ନାମଲେଖା ତାଲିମାର୍ଥୀ' },
  male_trainees: { en: 'Male Trainees', or: 'ପୁରୁଷ ତାଲିମାର୍ଥୀ' },
  female_trainees: { en: 'Female Trainees', or: 'ମହିଳା ତାଲିମାର୍ଥୀ' },
  sc_trainees: { en: 'SC Trainees', or: 'ଅନୁସୂଚିତ ଜାତି ତାଲିମାର୍ଥୀ' },
  st_trainees: { en: 'ST Trainees', or: 'ଅନୁସୂଚିତ ଜନଜାତି ତାଲିମାର୍ଥୀ' },
  obc_trainees: { en: 'OBC Trainees', or: 'OBC ତାଲିମାର୍ଥୀ' },
  ews_trainees: { en: 'EWS Trainees', or: 'EWS ତାଲିମାର୍ଥୀ' },
  general_trainees: { en: 'General Trainees', or: 'ସାଧାରଣ ବର୍ଗ ତାଲିମାର୍ଥୀ' },
  minority_trainees: { en: 'Minority Trainees', or: 'ସଂଖ୍ୟାଲଘୁ ତାଲିମାର୍ଥୀ' },
  pwd_trainees: { en: 'PWD Trainees', or: 'ଭିନ୍ନକ୍ଷମ ତାଲିମାର୍ଥୀ' },
  host_state_trainees: { en: 'Host State Trainees', or: 'ନିଜ ରାଜ୍ୟ ତାଲିମାର୍ଥୀ' },
  other_state_trainees: { en: 'Other State Trainees', or: 'ଅନ୍ୟ ରାଜ୍ୟ ତାଲିମାର୍ଥୀ' },
  admission_mode: { en: 'Admission Mode', or: 'ନାମଲେଖା ପ୍ରଣାଳୀ' },
  minimum_entry_qualification: { en: 'Minimum Entry Qualification', or: 'ସର୍ବନିମ୍ନ ଯୋଗ୍ୟତା' },
  tuition_course_fee_per_year: { en: 'Tuition Fee (Per Year)', or: 'ବାର୍ଷିକ ଶିକ୍ଷା ଦେୟ' },
  govt_scholarships: { en: 'Govt Scholarships', or: 'ସରକାରୀ ବୃତ୍ତି' },
  institutional_scholarships: { en: 'Institutional Scholarships', or: 'ଅନୁଷ୍ଠାନିକ ବୃତ୍ତି' },
  total_instructors: { en: 'Total Instructors', or: 'ମୋଟ ପ୍ରଶିକ୍ଷକ' },
  total_instructors_regular: { en: 'Regular Instructors', or: 'ନିୟମିତ ପ୍ରଶିକ୍ଷକ' },
  total_instructors_contract: { en: 'Contractual Instructors', or: 'ଚୁକ୍ତିଭିତ୍ତିକ ପ୍ରଶିକ୍ଷକ' },
  total_instructors_with_cits: { en: 'Instructors with CITS', or: 'CITS ପ୍ରାପ୍ତ ପ୍ରଶିକ୍ଷକ' },
  total_instructors_with_nac_ntc_iti: { en: 'Instructors with NAC/NTC/ITI', or: 'NAC/NTC/ITI ପ୍ରଶିକ୍ଷକ' },
  total_instructors_with_industry_experience: { en: 'Instructors with Industry Exp.', or: 'ଶିଳ୍ପ ଅଭିଜ୍ଞତା ପ୍ରଶିକ୍ଷକ' },
  total_workshop_staff: { en: 'Workshop Staff', or: 'ୱାର୍କସପ୍ କର୍ମଚାରୀ' },
  central_library_reading_room: { en: 'Central Library/Reading Room', or: 'କେନ୍ଦ୍ରୀୟ ପାଠାଗାର/ପଠନ ଗୃହ' },
  library_books_count: { en: 'Library Books Count', or: 'ପାଠାଗାର ବହି ସଂଖ୍ୟା' },
  digital_learning_materials: { en: 'Digital Learning Materials', or: 'ଡିଜିଟାଲ୍ ଶିକ୍ଷା ସାମଗ୍ରୀ' },
  computer_lab: { en: 'Computer Lab', or: 'କମ୍ପ୍ୟୁଟର ଲ୍ୟାବ୍' },
  total_computers: { en: 'Total Computers', or: 'ମୋଟ କମ୍ପ୍ୟୁଟର' },
  wifi_campus: { en: 'WiFi Campus', or: 'ୱାଇ-ଫାଇ କ୍ୟାମ୍ପସ' },
  no_of_theory_classrooms: { en: 'Theory Classrooms', or: 'ଥିଓରି ଶ୍ରେଣୀକକ୍ଷ' },
  no_of_workshops: { en: 'No of Workshops', or: 'ୱାର୍କସପ୍ ସଂଖ୍ୟା' },
  equipment_as_per_ncvt_norms: { en: 'Equipment as per NCVT', or: 'NCVT ଅନୁସାରେ ସାମଗ୍ରୀ' },
  safety_equipment_available: { en: 'Safety Equipment', or: 'ସୁରକ୍ଷା ସାମଗ୍ରୀ' },
  power_supply: { en: 'Power Supply', or: 'ବିଦ୍ୟୁତ୍ ଯୋଗାଣ' },
  power_backup: { en: 'Power Backup', or: 'ବିଦ୍ୟୁତ୍ ବ୍ୟାକ୍-ଅପ୍' },
  toilets_details: { en: 'Toilets Details', or: 'ଶୌଚାଳୟ ବିବରଣୀ' },
  ramp_accessibility: { en: 'Ramp/Accessibility', or: 'ରାମ୍ପ ସୁବିଧା' },
  facilities_for_pwd: { en: 'Facilities for PWD', or: 'ଭିନ୍ନକ୍ଷମଙ୍କ ପାଇଁ ସୁବିଧା' },
  playground: { en: 'Playground', or: 'ଖେଳ ପଡିଆ' },
  indoor_games: { en: 'Indoor Games', or: 'ଇନଡୋର ଗେମ୍ସ' },
  first_aid_health_room: { en: 'First Aid Room', or: 'ପ୍ରାଥମିକ ଚିକିତ୍ସା କକ୍ଷ' },
  fire_safety_system: { en: 'Fire Safety', or: 'ଅଗ୍ନି ନିର୍ବାପକ ବ୍ୟବସ୍ଥା' },
  industry_partner: { en: 'Industry Partner', or: 'ଶିଳ୍ପ ସହଭାଗୀ' },
  industry_partners_list: { en: 'Industry Partners', or: 'ଶିଳ୍ପ ସହଭାଗୀ ସମୂହ' },
  mous_with_industry_count: { en: 'MOUs with Industry', or: 'ଶିଳ୍ପ ସହ MOU ସଂଖ୍ୟା' },
  career_guidance_cell: { en: 'Career Guidance Cell', or: 'କ୍ୟାରିୟର ମାର୍ଗଦର୍ଶନ' },
  training_placement_cell: { en: 'Training & Placement Cell', or: 'ପ୍ରଶିକ୍ଷଣ ଓ ନିଯୁକ୍ତି' },
  tpo_name: { en: 'TPO Name', or: 'TPO ନାମ' },
  tpo_contact: { en: 'TPO Contact', or: 'TPO ଯୋଗାଯୋଗ' },
  on_job_training_mandatory: { en: 'On-Job Training (OJT)', or: 'କାର୍ଯ୍ୟକାଳୀନ ପ୍ରଶିକ୍ଷଣ (OJT)' },
  trainees_completing_last_year_percent: { en: 'Completion % (Last Year)', or: 'ସମାପ୍ତି % (ଗତ ବର୍ଷ)' },
  campus_interviews_held_last_year_count: { en: 'Campus Interviews', or: 'କ୍ୟାମ୍ପସ ସାକ୍ଷାତକାର' },
  companies_visited_last_year: { en: 'Companies Visited', or: 'ଆସିଥିବା କମ୍ପାନୀ ସମୂହ' },
  trainees_placed_last_year_count: { en: 'Placed Trainees', or: 'ନିଯୁକ୍ତି ତାଲିମାର୍ଥୀ' },
  average_salary_monthly: { en: 'Average Salary (Monthly)', or: 'ହାରାହାରି ମାସିକ ଦରମା' },
  highest_salary_monthly: { en: 'Highest Salary (Monthly)', or: 'ସର୍ବାଧିକ ମାସିକ ଦରମା' },
  trainees_starting_self_employment_count: { en: 'Self-employment Count', or: 'ସ୍ୱ-ନିୟୋଜିତତା ସଂଖ୍ୟା' },
  trainees_going_for_higher_studies_count: { en: 'Higher Studies Count', or: 'ଉଚ୍ଚଶିକ୍ଷା ସଂଖ୍ୟା' },
  soft_skills_training: { en: 'Soft Skills Training', or: 'ସଫ୍ଟ ସ୍କିଲ୍ସ ପ୍ରଶିକ୍ଷଣ' },
  digital_ict_training: { en: 'Digital/ICT Training', or: 'ଡିଜିଟାଲ୍/ICT ପ୍ରଶିକ୍ଷଣ' },
  value_added_short_term_courses: { en: 'Short-term Courses', or: 'ସ୍ୱଳ୍ପ ମିଆଦି ପାଠ୍ୟକ୍ରମ' },
  awards_recognition: { en: 'Awards & Recognition', or: 'ପୁରସ୍କାର ଓ ସ୍ୱୀକୃତି' },
  special_initiatives: { en: 'Special Initiatives', or: 'ସ୍ୱତନ୍ତ୍ର ପଦକ୍ଷେପ' },
  clubs: { en: 'Clubs', or: 'କ୍ଲବ୍' },
  iti_phone: { en: 'ITI Phone', or: 'ITI ଫୋନ୍' },
  iti_email: { en: 'ITI Email', or: 'ITI ଇମେଲ୍' },
  // Extra ITI profile helpers
  total_non_teaching_staff: { en: 'Total Non-Teaching Staff', or: 'ମୋଟ ଅଶିକ୍ଷକ କର୍ମଚାରୀ' },
  principal_superintendent_name: { en: 'Principal/Superintendent Name', or: 'ପ୍ରିନ୍ସିପାଲ୍/ସୁପରିଣ୍ଟେଣ୍ଡେଣ୍ଟ ନାମ' },
};

const HEALTH_LABELS: Record<string, string> = {
  block_ulb: 'Block / ULB',
  gp_ward: 'GP / Ward',
  village: 'Village',
  latitude: 'Latitude',
  longitude: 'Longitude',
  name: 'Name',
  category: 'Category',
  inst_head_name: 'Inst Head Name',
  inst_head_contact: 'Inst Head Contact',
  no_of_ts: 'No of TS',
  no_of_nts: 'No of NTS',
  no_of_mo: 'No of MO',
  no_of_pharmacist: 'No of Pharmacist',
  no_of_anm: 'No of ANM',
  no_of_health_worker: 'No of Health Worker',
  no_of_pathology: 'No of Pathology',
  no_of_clerk: 'No of Clerk',
  no_of_sweeper: 'No of Sweeper',
  no_of_nw: 'No of NW',
  no_of_bed: 'No of Bed',
  no_of_icu: 'No of ICU',
  x_ray_availabilty: 'X-Ray Availability',
  ct_scan_availability: 'CT-Scan Availability',
  availability_of_pathology_testing: 'Availability of Pathology Testing',
  description: 'Description',
};

export function getEducationProfileLabel(key: string, language: Language = 'en'): string {
  const labelObj = EDUCATION_LABELS[key];
  if (labelObj) {
    return labelObj[language] || labelObj.en;
  }
  return titleCase(key);
}

export function getHealthProfileLabel(key: string): string {
  return HEALTH_LABELS[key] ?? titleCase(key);
}

const MINOR_IRRIGATION_LABELS: Record<string, { en: string; or: string }> = {
  block_ulb: { en: 'Block / ULB', or: 'ବ୍ଲକ୍ / ULB' },
  gp_ward: { en: 'GP / Ward', or: 'ଜି.ପି. / ୱାର୍ଡ' },
  village_locality: { en: 'Village / Locality', or: 'ଗ୍ରାମ / ଅଞ୍ଚଳ' },
  mip_id: { en: 'MIP ID', or: 'MIP ଆଇଡି' },
  name_of_m_i_p: { en: 'Name of M.I.P', or: 'M.I.P ର ନାମ' },
  category_type: { en: 'Category / Type', or: 'ଶ୍ରେଣୀ / ପ୍ରକାର' },
  category: { en: 'Category', or: 'ଶ୍ରେଣୀ' },
  latitude: { en: 'Latitude', or: 'ଅକ୍ଷାଂଶ' },
  longitude: { en: 'Longitude', or: 'ଦ୍ରାଘିମାଂଶ' },
  latitude_raw: { en: 'Latitude (raw)', or: 'ଅକ୍ଷାଂଶ (ମୂଳ)' },
  longitude_raw: { en: 'Longitude (raw)', or: 'ଦ୍ରାଘିମାଂଶ (ମୂଳ)' },
  location_precision_meter: { en: 'Location precision (meter)', or: 'ଅବସ୍ଥାନ ସଠିକତା (ମିଟର)' },
  catchment_area_sq_km: { en: 'Catchment area (sq km)', or: 'କ୍ୟାଚମେଣ୍ଟ କ୍ଷେତ୍ରଫଳ (ଚ.କି.ମି.)' },
  command_area_kharif_acres: { en: 'Command area kharif (acres)', or: 'କମାଣ୍ଡ ଏରିଆ ଖରିଫ (ଏକର)' },
  command_area_rabi_acres: { en: 'Command area rabi (acres)', or: 'କମାଣ୍ଡ ଏରିଆ ରବି (ଏକର)' },
  total_ayacut_acres: { en: 'Total ayacut (acres)', or: 'ମୋଟ ଆୟାକଟ୍ (ଏକର)' },
  storage_capacity_mcum: { en: 'Storage capacity (MCUM)', or: 'ସଂରକ୍ଷଣ କ୍ଷମତା (MCUM)' },
  mwl_ft: { en: 'MWL (ft)', or: 'MWL (ଫୁଟ୍)' },
  frl_ft: { en: 'FRL (ft)', or: 'FRL (ଫୁଟ୍)' },
  tbl_ft: { en: 'TBL (ft)', or: 'TBL (ଫୁଟ୍)' },
  spillway_type: { en: 'Spillway type', or: 'ସ୍ପିଲୱେ ପ୍ରକାର' },
  spillway_width_ft: { en: 'Spillway width (ft)', or: 'ସ୍ପିଲୱେ ପ୍ରସ୍ଥ (ଫୁଟ୍)' },
  no_of_sluices: { en: 'No. of sluices', or: 'ସ୍ଲୁଇସ୍ ସଂଖ୍ୟା' },
  sluice_type: { en: 'Sluice type', or: 'ସ୍ଲୁଇସ୍ ପ୍ରକାର' },
  condition: { en: 'Condition', or: 'ଅବସ୍ଥା' },
  functionality: { en: 'Functionality', or: 'କାର୍ଯ୍ୟକ୍ଷମତା' },
  managed_by: { en: 'Managed by', or: 'ପରିଚାଳନା କରୁଥିବା' },
  last_maintenance: { en: 'Last maintenance', or: 'ଶେଷ ରକ୍ଷାଣାବେକ୍ଷଣ' },
  sensors_installed: { en: 'Sensors installed', or: 'ସେନ୍ସର ଲଗାଇଛନ୍ତି' },
  last_geotagged_date: { en: 'Last geotagged date', or: 'ଶେଷ ଜିଓ-ଟ୍ୟାଗ୍ ତାରିଖ' },
  beneficiary_farmers_count: { en: 'Beneficiary farmers count', or: 'ଲାଭାନ୍ବିତ କୃଷକ ସଂଖ୍ୟା' },
  beneficiary_households: { en: 'Beneficiary households', or: 'ଲାଭାନ୍ବିତ ଘରୋଇ ପରିବାର' },
  beneficiary_sc_st_count: { en: 'Beneficiary SC/ST count', or: 'ଲାଭାନ୍ବିତ SC/ST ସଂଖ୍ୟା' },
  sanctioned_amt_lakhs: { en: 'Sanctioned amount (lakhs)', or: 'ମଞ୍ଜୁର ରାଶି (ଲକ୍ଷ)' },
  expenditure_lakhs: { en: 'Expenditure (lakhs)', or: 'ବ୍ୟୟ (ଲକ୍ଷ)' },
  forest_clearance_y_n: { en: 'Forest clearance (Y/N)', or: 'ବନ ମଞ୍ଜୁରୀ (ହଁ/ନା)' },
  remarks: { en: 'Remarks', or: 'ମନ୍ତବ୍ୟ' },
  // Irrigation department specific (from irrigation CSV)
  type_of_irrigation_flowliftsolar: { en: 'Type of irrigation', or: 'ସେଚନ ପ୍ରକାର' },
  'catchment_area_in_sq_km.': { en: 'Catchment area (sq km)', or: 'କ୍ୟାଚମେଣ୍ଟ କ୍ଷେତ୍ରଫଳ (ଚ.କି.ମି.)' },
  'command_area__ayacut_ha.': { en: 'Command / Ayacut (ha.)', or: 'କମାଣ୍ଡ / ଆୟାକଟ୍ (ହେକ୍ଟର୍)' },
  // CSV variant with single underscore between "area" and "ayacut"
  'command_area_ayacut_ha.': { en: 'Command / Ayacut (ha.)', or: 'କମାଣ୍ଡ / ଆୟାକଟ୍ (ହେକ୍ଟର୍)' },
  'storage_capacity_ham.': { en: 'Storage capacity (HAM.)', or: 'ସଂରକ୍ଷଣ କ୍ଷମତା (HAM.)' },
  'water_spread_area_ha.': { en: 'Water spread area (ha.)', or: 'ଜଳ ବିସ୍ତାର କ୍ଷେତ୍ରଫଳ (ହେକ୍ଟର୍)' },
  canal_distributory_length_km: { en: 'Canal / distributory length (km)', or: 'କ୍ୟାନାଲ୍ / ବଣ୍ଟନୀ ଲମ୍ବ (କି.ମି.)' },
  design_discharge_cusecs: { en: 'Design discharge (cusecs)', or: 'ଡିଜାଇନ୍ ଡିସଚାର୍ଜ୍ (କ୍ୟୁସେକ୍ସ୍)' },
  inflow_source_riverrainstream__canal: { en: 'Inflow source', or: 'ଜଳ ଆଗମନ ସ୍ରୋତ' },
  // CSV variant with underscores between words
  inflow_source_river_rain_stream_canal: { en: 'Inflow source', or: 'ଜଳ ଆଗମନ ସ୍ରୋତ' },
  year_of_commissioning: { en: 'Year of commissioning', or: 'ଚାଲୁ ହେବାର ବର୍ଷ' },
  current_physical_condition_good_repair_needed_critical: {
    en: 'Physical condition',
    or: 'ଭୂତଳ ଅବସ୍ଥା',
  },
  functionality_status_functional_partial_non_functional: {
    en: 'Functionality status',
    or: 'କାର୍ଯ୍ୟକ୍ଷମତା ସ୍ଥିତି',
  },
  managed_by_pani_panchayatdeptwua: { en: 'Managed by', or: 'ପରିଚାଳନା କରୁଥିବା' },
  // CSV variant with underscores between words
  managed_by_pani_panchayat_dept_wua: { en: 'Managed by', or: 'ପରିଚାଳନା କରୁଥିବା' },
  last_maintenancedesilting_year: {
    en: 'Last maintenance / desilting year',
    or: 'ଶେଷ ରକ୍ଷାଣାବେକ୍ଷଣ / ଡି-ସିଲ୍ଟିଂ ବର୍ଷ',
  },
  // CSV variant with underscore before "desilting"
  last_maintenance_desilting_year: {
    en: 'Last maintenance / desilting year',
    or: 'ଶେଷ ରକ୍ଷାଣାବେକ୍ଷଣ / ଡି-ସିଲ୍ଟିଂ ବର୍ଷ',
  },
  water_availability_monthsyear: { en: 'Water availability (months / year)', or: 'ଜଳ ଉପଲବ୍ଧତା (ମାସ / ବର୍ଷ)' },
  // CSV variant with underscore between "months" and "year"
  water_availability_months_year: {
    en: 'Water availability (months / year)',
    or: 'ଜଳ ଉପଲବ୍ଧତା (ମାସ / ବର୍ଷ)',
  },
  funding_scheme_mgnregsstatecentral: { en: 'Funding scheme', or: 'ଅର୍ଥାୟନ ଯୋଜନା' },
  // CSV variant with underscores between "mgnregs", "state", "central"
  funding_scheme_mgnregs_state_central: { en: 'Funding scheme', or: 'ଅର୍ଥାୟନ ଯୋଜନା' },
  remarks_historical_background: { en: 'Remarks / historical background', or: 'ମନ୍ତବ୍ୟ / ଐତିହାସିକ ପୃଷ୍ଠଭୂମି' },
};

export function getMinorIrrigationProfileLabel(
  key: string,
  language: Language = 'en',
): string {
  const labelObj = MINOR_IRRIGATION_LABELS[key];
  if (labelObj) return labelObj[language] || labelObj.en;
  return titleCase(key);
}

/** All known education keys in display order (for template when data is empty). */
export const EDUCATION_PROFILE_KEYS = Object.keys(EDUCATION_LABELS);

/** All known health keys in display order. */
export const HEALTH_PROFILE_KEYS = Object.keys(HEALTH_LABELS);

/** All known minor irrigation keys in display order. */
export const MINOR_IRRIGATION_PROFILE_KEYS = Object.keys(MINOR_IRRIGATION_LABELS);
